### ISSUE TITLE
Add a handler for status changes

### ISSUE THREAD

**Issue by viestat** [ridedott/dependabot-auto-merge-action#16]
**What do you want to achieve?**
Some repos like [functions](https://github.com/ridedott/functions) relies on status as well as on check_suite events.

**What is the current way of working?**
Currently there is no handler for status changes

**How much does it hurt?**
This action will not be accommodating to the needs of repos like [functions](https://github.com/ridedott/functions)

**Comment by merlinnot** [comment]
Resolved in #8.
