### ISSUE TITLE
Prevent multiple review approvals

### ISSUE THREAD

**Issue by viestat** [ridedott/dependabot-auto-merge-action#17]
**What do you want to achieve?**
Add some logic to prevent the action to approve a PR multiple times as seen here https://github.com/ridedott/test-workflows/pull/4

**What is the current way of working?**
Currently there is no logic to prevent this behaviour in the action

**How much does it hurt?**
A lot of unnecessary approvals makes the PR messy

**Comment by viestat** [comment]
We should add a check for the `check_suite` conclusion:
`checkSuite.conclusion === 'success'`

_Originally posted by @acazacu in https://github.com/ridedott/auto-merge-action/pull/8_

**Comment by merlinnot** [comment]
Resolved by #23
